name: ESLint & Prettier Format

on:
    push:
        branches: ['development']
    pull_request:
        branches: ['development']
    schedule:
        - cron: '18 11 * * 5'

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: Run NPM format
              run: npm run format