name: Jest

on:
    push:
        branches:
            - development
    pull_request:
        branches:
            - development

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: Install sqlite3
              run: npm install sqlite3
            
            - name: Rename config
              run: mv config.example.json config.json

            - name: Run tests
              run: npm test
