name: Jest Coverage

on:
    push:
        branches: ['development']
    pull_request:
        branches: ['development']
    schedule:
        - cron: '18 11 * * 5'

jobs:
    test-and-generate-coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: Create cache directory
              run: mkdir -p .cache

            - name: Create and populate cache file
              run: |
                  echo '{"server":{"serverName":"name","uuid":"73d18214-f52f-4498-9bfc-4503b92acdfb","location":"location","secret":"xDlWI`6ipto(6jFzjQ5<G3<0h3+?AJcYRo0KPI6V@3JgvGt%k+g3fGNmNplqKc`Z","secretPhrase":"secret secret secret secret","apiKey":"2p7FFxCZCt7feZW1llcBe7cakOj7bQKR/wIwKBjskYU="},"lastDatabaseLoaded": "MariaDB"}' > .cache/cache.json

            - name: Rename config
              run: mv config.example.json config.json

            - name: Run tests and generate coverage report
              run: npm run coverage

            - name: Upload code coverage artifact
              uses: actions/upload-artifact@v2
              with:
                  name: coverage
                  path: coverage
